import React from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Method='classic'|'yolo'|'both';
type Frame={index:number;timestamp_ms:number;led_state:number[];confidences:number[];mean_confidence:number;processing_time_ms:number;locator_status:string;detection_view_url:string;image_url:string};
type Result={method:'classic'|'yolo';frames:Frame[];temporal_pattern:Record<string,string>;predicted_error_code:string|null;error_description:string|null;match_score:number;match_margin:number;mean_detector_latency_ms:number};
type Job={id:string;status:string;stage:string;progress:number;message:string;frames_captured:number;methods:Result[];total_duration_seconds:number|null;error:string|null};
const stages=['capturing','extracting_frames','detecting_leds','temporal_analysis','matching_error_code','result'];
const labels:Record<string,string>={capturing:'Capturing',extracting_frames:'Extracting Frames',detecting_leds:'Detecting LEDs',temporal_analysis:'Temporal Analysis',matching_error_code:'Matching Error Code',result:'Result'};

function Leds({states}:{states:(number|string)[]}){return <div className="leds">{states.map((s,i)=><span key={i} className={`led ${s===1||s==='on'?'on':s===0||s==='off'?'off':String(s).startsWith('blink')?'blink':'unknown'}`} title={String(s)} />)}</div>}
function App(){
 const [health,setHealth]=React.useState<{status:string;yolo_available:boolean;yolo_reason?:string}>({status:'connecting',yolo_available:false});
 const [cameras,setCameras]=React.useState<{index:number;name:string}[]>([]); const [method,setMethod]=React.useState<Method>('classic');
 const [source,setSource]=React.useState<'camera'|'video'>('camera'); const [camera,setCamera]=React.useState(0); const [duration,setDuration]=React.useState(3); const [fps,setFps]=React.useState(6); const [video,setVideo]=React.useState('');
 const [job,setJob]=React.useState<Job|null>(null); const [error,setError]=React.useState(''); const [view,setView]=React.useState<'camera'|'detection'>('detection');
 const refresh=React.useCallback(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setHealth({status:'offline',yolo_available:false}));fetch('/api/cameras').then(r=>r.json()).then(d=>setCameras(d.cameras)).catch(()=>setCameras([]))},[]);
 React.useEffect(refresh,[refresh]);
 React.useEffect(()=>{if(!job||['complete','failed'].includes(job.status))return;const timer=setInterval(async()=>{const r=await fetch(`/api/analysis/${job.id}`);if(r.ok)setJob(await r.json())},300);return()=>clearInterval(timer)},[job]);
 async function start(){setError('');setJob(null);const response=await fetch('/api/analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({method,source,camera_index:camera,video_path:video||null,duration_seconds:duration,analysis_fps:fps,width:1280,height:720})});const data=await response.json();if(!response.ok){setError(data.detail||'Could not start analysis');return}setJob({id:data.id,status:'queued',stage:'capturing',progress:0,message:'Queued',frames_captured:0,methods:[],total_duration_seconds:null,error:null})}
 const activeStage=job?Math.max(0,stages.indexOf(job.stage)):0; const working=job&&!['complete','failed'].includes(job.status);
 return <main><header><div><p className="eyebrow">BACHELOR THESIS · LIVE DEMONSTRATION</p><h1>LED Pattern Recognition <span>– Live Analysis</span></h1><p className="subtitle">Classic Computer Vision vs. Deep Learning</p></div><div className="statusbar"><span><i className={health.status==='ok'?'good':'bad'}/>{health.status==='ok'?'Backend online':'Backend offline'}</span><span><i className={cameras.length?'good':'bad'}/>{cameras.length?'Camera connected':'Camera unavailable'}</span><span title={health.yolo_reason}><i className={health.yolo_available?'good':'warn'}/>{health.yolo_available?'YOLO ready':'YOLO unavailable'}</span></div></header>
 <section className="method-section"><div className="section-title"><b>01</b><div><h2>Select analysis method</h2><p>Choose how the captured LED sequence will be interpreted.</p></div></div><div className="methods">
 {([['classic','Classic Computer Vision','Rule-based detection using image-processing heuristics.'],['yolo','Deep Learning / YOLO','Learned LED detection using the trained YOLO model.'],['both','Compare Both','Run identical captured frames through both methods.']] as const).map(([key,title,desc])=><button key={key} disabled={key!=='classic'&&!health.yolo_available} className={`method ${method===key?'selected':''}`} onClick={()=>setMethod(key)}><span className="method-icon">{key==='classic'?'CV':key==='yolo'?'AI':'↔'}</span><span><strong>{title}</strong><small>{desc}</small>{key!=='classic'&&!health.yolo_available&&<em>Model unavailable</em>}</span><b className="radio"/></button>)}</div></section>
 <section className="workspace"><div className="camera-card"><div className="card-head"><div><p className="eyebrow">LIVE INPUT</p><h2>{source==='camera'?'USB Camera':'Fallback Video'}</h2></div><div className="segmented"><button className={source==='camera'?'active':''} onClick={()=>setSource('camera')}>Live Camera</button><button className={source==='video'?'active':''} onClick={()=>setSource('video')}>Video File</button></div></div>
 <div className="preview">{source==='camera'&&cameras.length?<img src={`/api/camera/${camera}/preview`} alt="Live camera preview"/>:<div className="empty"><span>▣</span><strong>{source==='camera'?'Camera not available':'Video fallback ready'}</strong><small>{source==='camera'?'Connect a camera or select Video File.':'Enter a local path in Settings.'}</small></div>}<div className="preview-label">{working?'● CAPTURING / ANALYSING':'LIVE PREVIEW'}</div></div>
 <details><summary>Analysis settings <span>⌄</span></summary><div className="settings"><label>Camera device<select value={camera} onChange={e=>setCamera(+e.target.value)}>{cameras.length?cameras.map(c=><option key={c.index} value={c.index}>{c.name}</option>):<option value="0">Camera 0</option>}</select></label><label>Capture duration<input type="number" min=".5" max="30" step=".5" value={duration} onChange={e=>setDuration(+e.target.value)}/><small>seconds</small></label><label>Analysis rate<input type="number" min=".2" max="30" value={fps} onChange={e=>setFps(+e.target.value)}/><small>frames / second</small></label>{source==='video'&&<label className="wide">Fallback video<input type="file" accept="video/*" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('Uploading fallback video…');const r=await fetch('/api/videos',{method:'POST',headers:{'X-Filename':file.name,'Content-Type':'application/octet-stream'},body:file});const d=await r.json();if(r.ok){setVideo(d.path);setError('')}else setError(d.detail||'Upload failed')}}/><small>{video?'Ready for live analysis':'Choose a local video file'}</small></label>}<button className="reset" onClick={()=>{setCamera(0);setDuration(3);setFps(6);setVideo('')}}>Reset defaults</button></div></details></div>
 <div className="flow-card"><p className="eyebrow">PROCESSING PIPELINE</p><div className="pipeline">{stages.map((s,i)=><React.Fragment key={s}><div className={`stage ${job&&i<=activeStage?'active':''} ${job&&i<activeStage?'done':''}`}><b>{i<activeStage?'✓':i+1}</b><span>{labels[s]}</span></div>{i<stages.length-1&&<i>↓</i>}</React.Fragment>)}</div><button className="start" disabled={!!working||health.status!=='ok'||(method!=='classic'&&!health.yolo_available)||(source==='video'&&!video)} onClick={start}>{working?<><span className="spinner"/>Analysis in progress</>:'Start Analysis'}<small>{method==='classic'?'CLASSIC CV':method==='yolo'?'DEEP LEARNING':'IDENTICAL FRAME COMPARISON'} · {duration.toFixed(1)} SEC</small></button>{job&&<div className="progress"><div style={{width:`${job.progress*100}%`}}/><p><b>{labels[job.stage]}</b><span>{job.message} · {Math.round(job.progress*100)}%</span></p></div>}{(error||job?.error)&&<div className="error">{error||job?.error}</div>}</div></section>
 {job?.status==='complete'&&<section className="results"><div className="section-title"><b>02</b><div><h2>Analysis result</h2><p>Individual detections are aggregated before matching the configured error codes.</p></div></div><div className={`result-grid ${job.methods.length>1?'compare':''}`}>{job.methods.map(result=><article className="result" key={result.method}><div className="complete">ANALYSIS COMPLETE · {result.method==='classic'?'CLASSIC CV':'DEEP LEARNING'}</div><p>Detected error code</p><h3>{result.predicted_error_code||'No matching error code detected'}</h3><p className="description">{result.error_description||'The temporal pattern did not produce a configured match.'}</p><div className="aggregate"><span>Temporally aggregated pattern</span><Leds states={Object.values(result.temporal_pattern)}/><code>{Object.values(result.temporal_pattern).join(' · ')}</code></div><div className="stats"><div><b>{result.frames.length}</b><span>Frames analysed</span></div><div><b>{result.mean_detector_latency_ms.toFixed(1)} ms</b><span>Mean latency / frame</span></div><div><b>{Math.round(result.match_score*100)}%</b><span>Pattern match</span></div><div><b>{job.total_duration_seconds?.toFixed(2)} s</b><span>Total analysis</span></div></div><div className="view-toggle"><b>Individual frame detections</b><span><button className={view==='camera'?'active':''} onClick={()=>setView('camera')}>Camera frame</button><button className={view==='detection'?'active':''} onClick={()=>setView('detection')}>Detection view</button></span></div><div className="filmstrip">{result.frames.map(frame=><div className="frame" key={frame.index}><img src={view==='detection'?frame.detection_view_url:frame.image_url}/><div><b>Frame {String(frame.index).padStart(2,'0')}</b><small>{(frame.timestamp_ms/1000).toFixed(2)} s · {frame.locator_status}</small></div><Leds states={frame.led_state}/><p>Confidence <b>{Math.round(frame.mean_confidence*100)}%</b></p><p>Processing <b>{frame.processing_time_ms.toFixed(1)} ms</b></p></div>)}</div></article>)}</div></section>}
 </main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
